const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.RADNOTE_CHROMIUM_PATH||undefined,args:['--no-sandbox']});const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setContent(fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8'));
assert.equal(await p.locator('#new').textContent(),'Neuer Befund');await p.selectOption('#language','en');assert.equal(await p.locator('#new').textContent(),'New report');await p.selectOption('#language','de');assert.equal(await p.locator('#new').textContent(),'Neuer Befund');
await p.locator('#findings').fill('Normal. Keep this phrase. Temporary.');await p.locator('#findings').evaluate(e=>e.setSelectionRange(8,25));await p.locator('#findings').locator('..').locator('.freeze-action').click();assert.equal(await p.locator('#frozen-findings button').count(),1);await p.locator('#findings').fill('');assert.equal(await p.locator('#findings').inputValue(),'Normal. Keep this phrase. Temporary.');p.on('dialog',d=>d.accept());await p.locator('#new').click();assert.equal(await p.locator('#findings').inputValue(),'Keep this phrase.');await p.locator('#frozen-findings button').click();await p.locator('#findings').fill('');assert.equal(await p.locator('#findings').inputValue(),'');
await p.selectOption('#template','freestyle');assert(await p.locator('#freestyle').isVisible());assert(!(await p.locator('#findings').isVisible()));await p.locator('#freestyle').fill('.pleura');await p.locator('#freestyle').press('Tab');assert.equal(await p.locator('#freestyle').inputValue(),'Kein Pleuraerguss oder Pneumothorax.');await p.locator('#freestyle').evaluate(e=>e.setSelectionRange(0,16));await p.locator('#freestyle-section .freeze-action').click();await p.locator('#new').click();assert.equal(await p.locator('#freestyle').inputValue(),'Kein Pleuraergus');
await p.locator('#macroFile').setInputFiles({name:'macros.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,macros:[{title:'Imported',code:'.import',text:'Loaded successfully'}]}))});await p.waitForFunction(()=>document.querySelector('#toast').textContent==='Textbausteine geladen');await p.locator('#freestyle-section .freeze-chip').click();await p.locator('#freestyle').fill('.import');await p.locator('#freestyle').press('Tab');assert.equal(await p.locator('#freestyle').inputValue(),'Loaded successfully');
await p.locator('#macroFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await p.waitForFunction(()=>document.querySelector('#toast').textContent==='Ungültige Textbausteindatei');assert(await p.locator('#macros').textContent().then(t=>t.includes('Imported')));
const dl=p.waitForEvent('download');await p.locator('#saveMacros').click();const downloaded=await dl;const data=JSON.parse(fs.readFileSync(await downloaded.path(),'utf8'));assert(data.macros.some(m=>m.code==='.import'));
const txt=p.waitForEvent('download');await p.locator('#export').click();const report=fs.readFileSync(await (await txt).path(),'utf8');assert(report.includes('FREIER BEFUND'));assert(!report.includes('KLINISCHE ANGABEN'));assert(report.includes('Loaded successfully'));assert.deepEqual(errors,[]);console.log('Passed: language switch, protected phrases, new report retention, unfreeze, freestyle, macro expansion, JSON import/export, invalid file handling, report export');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
