const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.RADNOTE_CHROMIUM_PATH||undefined,args:['--no-sandbox']});const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://radnote.test/**',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8')}));await p.goto('https://radnote.test/');await p.evaluate(()=>{window.copied=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>window.copied.push(text)}})});
await p.locator('#findings').fill('Only findings');await p.locator('#findings').locator('..').locator('.field-copy').click();assert.deepEqual(await p.evaluate(()=>copied),['Only findings']);
await p.selectOption('#template','combined');assert(await p.locator('#combined').isVisible());assert(await p.locator('#indication').isVisible());assert(!await p.locator('#findings').isVisible());assert(!await p.locator('#impression').isVisible());assert.equal(await p.locator('label[for=combined]').textContent(),'Befund und Beurteilung');await p.locator('#combined').fill('Combined text');await p.locator('#combined').locator('..').locator('.field-copy').click();assert.equal(await p.evaluate(()=>copied.at(-1)),'Combined text');
await p.locator('#addTemplate').click();await p.locator('#templateName').fill('Neuro');await p.locator('.template-field-name').fill('Anamnese');await p.locator('.template-field-default').fill('Standard history');await p.locator('#addTemplateField').click();await p.locator('.template-field-name').nth(1).fill('Zusammenfassung');await p.locator('.template-field-default').nth(1).fill('Baseline');await p.locator('#templateForm button.primary').click();let customId=await p.locator('#template').inputValue();assert(customId.startsWith('custom-'));let custom=p.locator('.section:visible textarea');assert.equal(await custom.count(),2);assert.equal(await custom.nth(0).inputValue(),'Standard history');assert.equal(await custom.nth(1).inputValue(),'Baseline');
await custom.nth(1).fill('.pleura');await custom.nth(1).press('Tab');assert.equal(await custom.nth(1).inputValue(),'Kein Pleuraerguss oder Pneumothorax.');await custom.nth(1).evaluate(e=>e.setSelectionRange(0,e.value.length));await custom.nth(1).locator('..').locator('.freeze-action').click();await custom.nth(1).fill('');assert.equal(await custom.nth(1).inputValue(),'Kein Pleuraerguss oder Pneumothorax.');await p.locator('#persist').check();await p.reload();assert.equal(await p.locator('#template').inputValue(),customId);assert.equal(await p.locator('.section:visible textarea').count(),2);assert.equal(await p.locator('.section:visible .freeze-chip').count(),1);p.on('dialog',d=>d.accept());await p.locator('#new').click();assert.equal(await custom.nth(0).inputValue(),'Standard history');assert.equal(await custom.nth(1).inputValue(),'Baseline\nKein Pleuraerguss oder Pneumothorax.');await p.locator('#new').click();assert.equal(await custom.nth(1).inputValue(),'Baseline\nKein Pleuraerguss oder Pneumothorax.');
await p.locator('#editTemplate').click();await p.locator('#templateName').fill('Neuro revised');await p.locator('.template-row').nth(1).getByText('Nach oben',{exact:true}).click();await p.locator('.template-field-name').nth(0).fill('Beurteilung individuell');await p.locator('#templateForm button.primary').click();assert.equal(await p.locator('.section:visible label').nth(0).textContent(),'Beurteilung individuell');assert.equal(await custom.nth(0).inputValue(),'Baseline\nKein Pleuraerguss oder Pneumothorax.');await p.selectOption('#language','en');assert.equal(await p.locator('.section:visible label').nth(0).textContent(),'Beurteilung individuell');assert.equal(await p.locator('.section:visible .field-copy').nth(0).textContent(),'Copy field');
const download=p.waitForEvent('download');await p.locator('#export').click();const data=fs.readFileSync(await (await download).path(),'utf8');assert(data.includes('BEURTEILUNG INDIVIDUELL'));assert(data.includes('ANAMNESE'));assert(!data.includes('Only findings'));
await p.locator('#editTemplate').click();await p.locator('#deleteTemplate').click();assert.equal(await p.locator('#template').inputValue(),'structured');assert.equal(await p.locator('#template option[data-custom]').count(),0);await p.reload();assert.equal(await p.locator('#template option[data-custom]').count(),0);assert.deepEqual(errors,[]);console.log('Passed: field copy, combined template, custom template creation/defaults/macros/freeze, reload persistence, new-report reset, edit/reorder, localization, export, delete');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
