const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.RADNOTE_CHROMIUM_PATH||undefined,args:['--no-sandbox']});const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://radnote.test/**',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(__dirname,'../index.html'),'utf8')}));await p.goto('https://radnote.test/');const f=p.locator('#findings');
for(const [input,expected] of [['re','rechts '],['Läsion re','Läsion rechts '],['(re','(rechts '],['unre','unre '],['.re','.re '],['Re','Re ']]){await f.fill(input);await f.press('Space');assert.equal(await f.inputValue(),expected)}
await f.fill('re, rest');await f.evaluate(e=>e.setSelectionRange(2,2));await f.press('Space');assert.equal(await f.inputValue(),'rechts , rest');assert.equal(await f.evaluate(e=>e.selectionStart),7);
await f.fill('re');await f.evaluate(e=>e.dispatchEvent(new InputEvent('beforeinput',{bubbles:true,cancelable:true,inputType:'insertText',data:' '})));assert.equal(await f.inputValue(),'rechts ');
await f.fill('re');await f.evaluate(e=>e.setSelectionRange(0,2));await f.locator('..').locator('.freeze-action').click();await f.evaluate(e=>e.setSelectionRange(2,2));await f.press('Space');assert.equal(await f.inputValue(),'re');await f.locator('..').locator('.freeze-chip').click();
await p.locator('#add').click();await p.selectOption('#macroTrigger','space');await p.locator('#macroTitle').fill('Links');await p.locator('#macroCode').fill('li');await p.locator('#macroText').fill('links');await p.locator('#macroForm button.primary').click();await f.fill('li');await f.press('Space');assert.equal(await f.inputValue(),'links ');await p.reload();await f.fill('li');await f.press('Space');assert.equal(await f.inputValue(),'links ');
await p.locator('#macroFile').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,macros:[{title:'Old tab macro',code:'.old',text:'Legacy works'}]}))});await p.waitForFunction(()=>document.querySelector('#toast').textContent==='Textbausteine geladen');await f.fill('.old');await f.press('Tab');assert.equal(await f.inputValue(),'Legacy works');
const dl=p.waitForEvent('download');await p.locator('#saveMacros').click();const data=JSON.parse(fs.readFileSync(await (await dl).path(),'utf8'));assert.equal(data.version,2);assert.equal(data.macros.find(m=>m.code==='li').trigger,'space');
await p.locator('#macroFile').setInputFiles({name:'word.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:2,macros:[{title:'Größe',code:'gr',text:'Größe',trigger:'space'}]}))});await p.waitForFunction(()=>document.querySelector('#toast').textContent==='Textbausteine geladen');await f.fill('gr');await f.press('Space');assert.equal(await f.inputValue(),'Größe ');
await p.selectOption('#template','freestyle');await p.locator('#freestyle').fill('li');await p.locator('#freestyle').press('Space');assert.equal(await p.locator('#freestyle').inputValue(),'links ');assert.deepEqual(errors,[]);console.log('Passed: Space expansion, whole-word boundaries, caret positions, beforeinput, frozen text, custom word macros, persistence, legacy import, typed macro export/import, freestyle');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
